#!/usr/bin/env python3
"""
A2 — deterministic bulk data generator for the deep-hierarchy schema (db/schema.sql).

Design (why it looks the way it does):

  * Deterministic. One seeded RNG drives every draw, so a given (--seed, --scale)
    always produces byte-identical data. That's what lets A3 plant golden records
    reproducibly and lets us diff loads.

  * Streaming COPY, not ORM. At ~10M rows, row-by-row INSERT/ORM is hopeless. We
    stream rows straight into Postgres `COPY ... FROM STDIN` (psycopg3), never
    materializing a table in memory.

  * The generator OWNS the ids. Ids are assigned 1..N per table by construction and
    written explicitly (schema uses GENERATED BY DEFAULT AS IDENTITY). Because we
    know every parent's id range up front, children pick coherent FKs with zero DB
    round-trips. After loading we bump each identity sequence past max(id).

  * Referential COHERENCE via contiguous allocation. Each parent owns a contiguous
    block of child ids (users of an entity, licenses of a master license, ...). So
    "a random user of this entity" is just base+randrange(count) — coherent and
    O(1), no per-row lookup tables for the huge tables.

Proportions emerge from per-parent draws (see BASE below); --scale multiplies the
entity count and everything else follows, keeping ratios stable at any size.

Run (small smoke test):
    LICENSING_PG_URL=postgresql://postgres:x@localhost:5433/lic \
        .venv/bin/python scripts/generate_bulk.py --reset --scale 0.003 --verify

Full ~10M-row load (minutes; point at Neon):
    LICENSING_PG_URL="$NEON_URL" .venv/bin/python scripts/generate_bulk.py --reset --scale 1.0

A3 — plant the demo scenario (Acme Corp / jane.doe / stale activation) on top
of the bulk load. --plant-demo requires --reset in the same invocation: it is
not idempotent (plain INSERTs, no upsert), so running it alone against an
already-populated DB would duplicate the demo rows on every rerun.
    LICENSING_PG_URL=postgresql://licensing:licensing@localhost:5433/licensing \
        .venv/bin/python scripts/generate_bulk.py --reset --plant-demo --verify
"""
from __future__ import annotations

import argparse
import os
import random
import sys
from datetime import date, datetime, timedelta

import psycopg

# ── Tunable model ────────────────────────────────────────────────────────────
# ENTITIES_FULL is the entity count at scale 1.0; --scale multiplies it and every
# other table follows from per-parent draws. Default scale is 0.1 (see argparse):
#   scale 0.1 → ~1,500 entities → ~1.5M rows / ~266 MB  (free-tier-sized)
#   scale 1.0 → ~15,000 entities → ~15M rows / ~2.6 GB  (local scale test only)
ENTITIES_FULL = 15_000
TODAY = date(2026, 7, 1)

ENTITY_TYPES = [("enterprise", 55), ("academic", 25), ("government", 10), ("individual", 10)]
LICENSE_STATUS = [("active", 80), ("expired", 12), ("trial", 5), ("suspended", 3)]
ENT_STATUS = [("active", 82), ("inactive", 8), ("hold", 3), ("review", 2), ("obsolete", 2), ("expired", 3)]
ACT_TYPE = [("standalone_named_user", 45), ("designated_computer", 25), ("concurrent", 20),
            ("network_named_user", 7), ("not_applicable", 2), ("unset", 1)]
SEAT_WEIGHTS = [(1, 10), (2, 8), (5, 6), (10, 5), (25, 3), (50, 2), (100, 1), (250, 1)]
TTL_DAYS = [30, 45, 90]
OS_POOL = [("Windows 11", 45), ("macOS 15", 30), ("Ubuntu 24.04", 20), ("RHEL 9", 5)]

FIRST = ["Jane", "Joe", "Amir", "Wei", "Priya", "Diego", "Sofia", "Liam", "Noah", "Mia",
         "Raj", "Yuki", "Omar", "Elena", "Kwame", "Anya", "Tom", "Sara", "Ivan", "Lena"]
LAST = ["Doe", "Chen", "Patel", "Garcia", "Kim", "Nguyen", "Muller", "Rossi", "Silva", "Khan",
        "Okafor", "Ito", "Haddad", "Novak", "Reyes", "Berg", "Ford", "Cruz", "Volkov", "Hart"]
ENAME_A = ["Acme", "Globex", "Initech", "Umbrella", "Stark", "Wayne", "Wonka", "Hooli",
           "Vehement", "Massive", "Soylent", "Vandelay", "Pied Piper", "Cyberdyne", "Gekko"]
ENAME_B = ["Corp", "Labs", "Systems", "Dynamics", "Industries", "Analytics", "Aerospace",
           "Robotics", "University", "Institute", "Motors", "Energy"]

# Product catalog: 18 atomic + 3 suites. Sampling uniformly gives ~14% suite lines.
ATOMIC = [
    ("ML", "MATLAB"), ("SL", "Simulink"), ("SF", "Stateflow"), ("SPT", "Signal Processing Toolbox"),
    ("IPT", "Image Processing Toolbox"), ("CVT", "Computer Vision Toolbox"), ("DLT", "Deep Learning Toolbox"),
    ("STAT", "Statistics and ML Toolbox"), ("OPT", "Optimization Toolbox"), ("CTRL", "Control System Toolbox"),
    ("SIMSCAPE", "Simscape"), ("EMBEDDED", "Embedded Coder"), ("HDL", "HDL Coder"), ("RTW", "Simulink Coder"),
    ("PARALLEL", "Parallel Computing Toolbox"), ("ROS", "ROS Toolbox"), ("DSP", "DSP System Toolbox"),
    ("COMMS", "Communications Toolbox"),
]
SUITES = [
    ("ACAD_SUITE", "Campus-Wide Suite", ["ML", "SL", "SF", "SPT", "IPT", "STAT", "OPT", "CTRL"]),
    ("CTRL_SUITE", "Control Design Suite", ["ML", "SL", "CTRL", "OPT", "SIMSCAPE"]),
    ("SIG_SUITE", "Signal & Comms Suite", ["ML", "SL", "SPT", "DSP", "COMMS", "CVT"]),
]


def weighted(rng: random.Random, pairs):
    """pairs = [(value, weight), ...] → one value."""
    total = sum(w for _, w in pairs)
    r = rng.uniform(0, total)
    upto = 0
    for v, w in pairs:
        upto += w
        if r <= upto:
            return v
    return pairs[-1][0]


def rand_date(rng, start: date, end: date) -> date:
    return start + timedelta(days=rng.randint(0, (end - start).days))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scale", type=float, default=0.1,
                    help="multiplies entity count. DEFAULT 0.1 ≈ 1.5M rows / ~266 MB (fits Neon free tier). "
                         "1.0 ≈ 15M rows / ~2.6 GB (needs a paid tier — use only for a local scale test).")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--reset", action="store_true", help="drop & recreate schema from db/schema.sql first")
    ap.add_argument("--verify", action="store_true", help="print row counts + FK integrity checks after load")
    ap.add_argument("--plant-demo", action="store_true",
                     help="plant one deterministic golden-record scenario (A3): Acme Corp / "
                          "L-DEMOACME / jane.doe@acmecorp.com / stale activation MAC-OLD-7291. "
                          "Requires --reset in the same invocation — not idempotent.")
    ap.add_argument("--url", default=os.environ.get("LICENSING_PG_URL"))
    args = ap.parse_args()
    if not args.url:
        ap.error("set --url or LICENSING_PG_URL")
    if args.plant_demo and not args.reset:
        ap.error("--plant-demo requires --reset in the same invocation — it is not "
                 "idempotent (plain INSERTs, no upsert) and would duplicate the demo "
                 "rows if run again against an already-populated DB")

    rng = random.Random(args.seed)
    n_entity = max(1, round(ENTITIES_FULL * args.scale))
    here = os.path.dirname(os.path.abspath(__file__))
    schema_path = os.path.join(here, "..", "db", "schema.sql")

    with psycopg.connect(args.url, autocommit=False) as conn:
        if args.reset:
            apply_schema(conn, schema_path)
            conn.commit()
            print(f"schema applied from {os.path.relpath(schema_path)}")

        load(conn, rng, n_entity)
        fix_sequences(conn)
        if args.plant_demo:
            plant_demo(conn)
        conn.commit()
        if args.verify:
            verify(conn)
    return 0


def apply_schema(conn, path):
    raw = open(path).read()
    # strip full-line comments; keep inline (no ';' inside our comments/strings)
    body = "\n".join(l for l in raw.splitlines() if not l.strip().startswith("--"))
    conn.execute("DROP SCHEMA public CASCADE")
    conn.execute("CREATE SCHEMA public")
    for stmt in body.split(";"):
        s = stmt.strip()
        if not s or s.upper() in ("BEGIN", "COMMIT"):
            continue
        conn.execute(s)


def copy_stream(conn, table, cols, rows):
    """Stream an iterable of tuples into COPY. Returns count."""
    n = 0
    with conn.cursor().copy(f"COPY {table} ({', '.join(cols)}) FROM STDIN") as cp:
        for row in rows:
            cp.write_row(row)
            n += 1
    return n


def load(conn, rng: random.Random, n_entity: int):
    import array

    # ── product catalog (fixed ids 1..P) ────────────────────────────────────
    code_to_id = {}
    prod_rows = []
    pid = 0
    for code, name in ATOMIC:
        pid += 1
        code_to_id[code] = pid
        prod_rows.append((pid, code, name, "toolbox" if code not in ("ML", "SL") else "core", False, 500 + pid * 10))
    suite_components = {}  # suite_pid -> [component_pid,...]
    for code, name, comps in SUITES:
        pid += 1
        code_to_id[code] = pid
        prod_rows.append((pid, code, name, "suite", True, 5000 + pid * 10))
        suite_components[pid] = [code_to_id[c] for c in comps]
    copy_stream(conn, "product", ["id", "product_code", "name", "category", "is_suite", "base_price"], prod_rows)
    for spid, comps in suite_components.items():
        copy_stream(conn, "product_suite_component", ["suite_product_id", "component_product_id"],
                    ((spid, c) for c in comps))
    all_pids = list(range(1, pid + 1))
    suite_pids = set(suite_components)
    print(f"product: {len(prod_rows)} ({len(suite_pids)} suites)")

    # ── entities + contiguous user blocks ───────────────────────────────────
    ent_user_start = array.array("q")
    ent_user_count = array.array("i")
    ent_domain = []
    ent_rows = []
    uid = 0
    for eid in range(1, n_entity + 1):
        etype = weighted(rng, ENTITY_TYPES)
        name = f"{rng.choice(ENAME_A)} {rng.choice(ENAME_B)} {eid}"
        dom = name.lower().replace(" ", "").replace(",", "")[:24] + f"{eid}.example"
        ent_domain.append(dom)
        ucount = max(3, int(rng.gauss(100, 45)))
        ent_user_start.append(uid + 1)
        ent_user_count.append(ucount)
        uid += ucount
        ent_rows.append((eid, name, etype, rng.choice(["Aerospace", "Auto", "Energy", "Semiconductor",
                        "Finance", "Academia", "Defense", "Medical"]),
                        rng.choice(["US", "DE", "IN", "JP", "GB", "FR", "CA"]),
                        rng.choice(["NA", "EMEA", "APAC"]), f"CDS-{eid:08d}"))
    copy_stream(conn, "entity", ["id", "name", "entity_type", "industry", "country", "region", "external_ref"], ent_rows)
    print(f"entity: {n_entity}")

    # ── app_user (contiguous per entity) ────────────────────────────────────
    def user_rows():
        for e in range(n_entity):
            start, cnt = ent_user_start[e], ent_user_count[e]
            dom = ent_domain[e]
            for u in range(start, start + cnt):
                fn, ln = rng.choice(FIRST), rng.choice(LAST)
                yield (u, 900_000_000 + u, f"{fn.lower()}.{ln.lower()}{u}@{dom}", fn, ln, e + 1)
    n_users = copy_stream(conn, "app_user",
                          ["id", "web_profile_id", "email", "first_name", "last_name", "entity_id"], user_rows())
    print(f"app_user: {n_users}")

    def pick_user(entity_idx):
        return ent_user_start[entity_idx] + rng.randrange(ent_user_count[entity_idx])

    def sample_users(entity_idx, k):
        cnt = ent_user_count[entity_idx]
        k = min(k, cnt)
        start = ent_user_start[entity_idx]
        return [start + off for off in rng.sample(range(cnt), k)]

    # ── master_license (contiguous per entity) ──────────────────────────────
    ml_entity = array.array("i")
    ml_rows = []
    mid = 0
    for e in range(n_entity):
        for _ in range(weighted(rng, [(1, 40), (2, 35), (3, 25)])):
            mid += 1
            ml_entity.append(e)  # entity index (0-based)
            ml_rows.append((mid, f"ML-{mid:07d}", e + 1,
                            f"{ent_rows[e][1]} Master", rng.choice(["DEV", "EDU", "GOV", "STD"]),
                            rng.choice(["STANDARD", "SPONSORED", "INTERNAL"])))
    copy_stream(conn, "master_license",
                ["id", "master_license_ref", "entity_id", "label", "program", "sponsor"], ml_rows)
    n_ml = mid
    print(f"master_license: {n_ml}")

    # ── license (contiguous per master_license) ─────────────────────────────
    lic_entity = array.array("i")
    lic_master = array.array("i")
    lic_rows = []
    lid = 0
    for m in range(1, n_ml + 1):
        e = ml_entity[m - 1]
        for _ in range(max(1, int(rng.gauss(12, 6)))):
            lid += 1
            lic_entity.append(e)
            lic_master.append(m)
            start = rand_date(rng, date(2023, 1, 1), date(2026, 3, 1))
            lic_rows.append((lid, f"L-{lid:07d}", m, weighted(rng, LICENSE_STATUS),
                             start, start + timedelta(days=365)))
    copy_stream(conn, "license",
                ["id", "license_ref", "master_license_id", "status", "start_date", "expiry_date"], lic_rows)
    n_lic = lid
    print(f"license: {n_lic}")

    # ── license_product (per license) + unallocated (per master license) ────
    # Store per-lp ancestry for allocated lps only (they spawn entitlements).
    lp_entity = array.array("i")
    lp_license = array.array("i")
    lp_master = array.array("i")
    lp_product = array.array("i")
    lp_id_arr = array.array("q")  # actual lp id (allocated only)

    def lp_rows():
        nonlocal_id = {"v": 0}

        def emit(mlid, licid, prodid, ent_idx, allocated):
            nonlocal_id["v"] += 1
            lpid = nonlocal_id["v"]
            if allocated:
                lp_id_arr.append(lpid)
                lp_entity.append(ent_idx)
                lp_license.append(licid)
                lp_master.append(mlid)
                lp_product.append(prodid)
            return (lpid, mlid, licid, prodid, weighted(rng, SEAT_WEIGHTS), 4000 + prodid)

        # allocated: per license
        for li in range(1, n_lic + 1):
            e = lic_entity[li - 1]
            m = lic_master[li - 1]
            k = max(1, int(rng.gauss(3.5, 1.8)))
            for prod in rng.sample(all_pids, min(k, len(all_pids))):
                yield emit(m, li, prod, e, True)
        # unallocated: per master license (license_id NULL)
        for m in range(1, n_ml + 1):
            e = ml_entity[m - 1]
            for _ in range(weighted(rng, [(0, 75), (1, 20), (2, 5)])):
                yield emit(m, None, rng.choice(all_pids), e, False)

    n_lp = copy_stream(conn, "license_product",
                       ["id", "master_license_id", "license_id", "product_id", "seat_count", "business_offering_id"],
                       lp_rows())
    n_alloc = len(lp_id_arr)
    print(f"license_product: {n_lp} ({n_alloc} allocated, {n_lp - n_alloc} unallocated)")

    # ── entitlement (fan out allocated lps: suite→components, atomic→1) ──────
    ent_entity = array.array("i")
    ent_rows_meta = []  # (entitlement_id, ...) built inline

    def entitlement_rows():
        eid = 0
        for i in range(n_alloc):
            lpid = lp_id_arr[i]
            prod = lp_product[i]
            lic = lp_license[i]
            m = lp_master[i]
            ent_idx = lp_entity[i]
            comps = suite_components[prod] if prod in suite_pids else [prod]
            for cprod in comps:
                eid += 1
                ent_entity.append(ent_idx)
                yield (eid, lic, m, lpid, cprod, "license", weighted(rng, ACT_TYPE),
                       weighted(rng, ENT_STATUS), None, rand_date(rng, date(2023, 6, 1), TODAY))
    n_ent = copy_stream(conn, "entitlement",
                        ["id", "license_id", "master_license_id", "license_product_id", "product_id",
                         "entitlement_type", "activation_type", "status", "label", "granted_at"],
                        entitlement_rows())
    print(f"entitlement: {n_ent}")

    # ── policy (1:1) ────────────────────────────────────────────────────────
    def policy_rows():
        for eid in range(1, n_ent + 1):
            mx = weighted(rng, [(1, 40), (2, 30), (5, 20), (25, 10)])
            yield (eid, eid, rng.choice(["Named User", "Concurrent", "Designated Computer"]),
                   weighted(rng, SEAT_WEIGHTS), mx, rng.choice(TTL_DAYS),
                   rng.random() < 0.3, weighted(rng, [(0, 60), (1, 25), (3, 15)]))
    copy_stream(conn, "policy",
                ["id", "entitlement_id", "policy_name", "quantity", "max_activations",
                 "activation_ttl_days", "allow_offline", "reactivation_limit"], policy_rows())
    print(f"policy: {n_ent}")

    # ── entitlement_person (assignment) ─────────────────────────────────────
    def ep_rows():
        pk = 0
        for eid in range(1, n_ent + 1):
            e = ent_entity[eid - 1]
            for u in sample_users(e, max(1, int(rng.gauss(1.6, 1.0)))):
                pk += 1
                yield (pk, eid, u, rng.choice(["user", "user", "user", "admin", "manager"]),
                       rand_date(rng, date(2023, 6, 1), TODAY),
                       "active" if rng.random() < 0.9 else "inactive")
    n_ep = copy_stream(conn, "entitlement_person",
                       ["id", "entitlement_id", "user_id", "role", "added_date", "status"], ep_rows())
    print(f"entitlement_person: {n_ep}")

    # ── activation (machine-level use; some deliberately stale) ─────────────
    def act_rows():
        pk = 0
        for eid in range(1, n_ent + 1):
            e = ent_entity[eid - 1]
            for _ in range(weighted(rng, [(0, 25), (1, 40), (2, 25), (3, 10)])):
                pk += 1
                u = pick_user(e)
                days_ago = weighted(rng, [(2, 30), (10, 25), (40, 20), (95, 15), (200, 10)])
                hb = datetime(TODAY.year, TODAY.month, TODAY.day) - timedelta(days=days_ago)
                yield (pk, eid, u, f"MW-{pk:010d}", rng.choice(["WS", "LT", "SRV"]) + f"-{pk % 9999}",
                       weighted(rng, OS_POOL), (hb - timedelta(days=rng.randint(1, 60))).date(),
                       hb, "active" if days_ago < 60 else "inactive")
    n_act = copy_stream(conn, "activation",
                        ["id", "entitlement_id", "user_id", "machine_id", "machine_name", "os",
                         "activation_date", "last_heartbeat", "status"], act_rows())
    print(f"activation: {n_act}")

    # ── license_end_user (seat membership per license) ──────────────────────
    def leu_rows():
        pk = 0
        for li in range(1, n_lic + 1):
            e = lic_entity[li - 1]
            for u in sample_users(e, max(1, int(rng.gauss(13, 8)))):
                pk += 1
                yield (pk, li, u, rand_date(rng, date(2023, 1, 1), TODAY),
                       "active" if rng.random() < 0.92 else "inactive")
    n_leu = copy_stream(conn, "license_end_user",
                        ["id", "license_id", "user_id", "added_date", "status"], leu_rows())
    print(f"license_end_user: {n_leu}")

    # ── master_license_admin (per master license) ───────────────────────────
    def admin_rows():
        pk = 0
        for m in range(1, n_ml + 1):
            e = ml_entity[m - 1]
            for u in sample_users(e, weighted(rng, [(1, 60), (2, 40)])):
                pk += 1
                yield (pk, m, u, rng.random() < 0.7, rand_date(rng, date(2023, 1, 1), TODAY))
    n_adm = copy_stream(conn, "master_license_admin",
                        ["id", "master_license_id", "user_id", "renewal_notifications", "added_date"], admin_rows())
    print(f"master_license_admin: {n_adm}")


def plant_demo(conn):
    """
    A3 — plant one deterministic golden-record scenario on top of the bulk
    data: Acme Corp / L-DEMOACME / jane.doe@acmecorp.com / a stale activation
    on MAC-OLD-7291. Fixed literal values, not RNG-driven — the point is a
    reproducible target for curl checks and demos (B2-READS-PLAN.md §9, §12).

    Must run after fix_sequences() so plain INSERTs (no explicit id) pick up
    ids past the bulk load's range, per schema.sql's own GENERATED BY DEFAULT
    convention (comment above CREATE TABLE product).
    """

    def insert_one(sql, params):
        return conn.execute(sql, params).fetchone()[0]

    acme_id = insert_one(
        "INSERT INTO entity (name, entity_type, industry, country, region, external_ref) "
        "VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
        ("Acme Corp", "enterprise", "Aerospace", "US", "NA", "ACME-DEMO-001"),
    )

    # jane.doe + 9 filler seat-holders (fills license_end_user to 10/10 on the
    # license) + 1 dedicated admin (master_license_admin only, not a seat holder).
    demo_users = [
        ("Jane", "Doe", "jane.doe"),
        ("Alex", "Kim", "alex.kim"),
        ("Bob", "Chen", "bob.chen"),
        ("Carol", "Patel", "carol.patel"),
        ("David", "Garcia", "david.garcia"),
        ("Elena", "Novak", "elena.novak"),
        ("Frank", "Silva", "frank.silva"),
        ("Grace", "Khan", "grace.khan"),
        ("Henry", "Ito", "henry.ito"),
        ("Iris", "Reyes", "iris.reyes"),
    ]
    user_ids = [
        insert_one(
            "INSERT INTO app_user (email, first_name, last_name, entity_id) "
            "VALUES (%s, %s, %s, %s) RETURNING id",
            (f"{local}@acmecorp.com", fn, ln, acme_id),
        )
        for fn, ln, local in demo_users
    ]
    jane_id = user_ids[0]

    admin_id = insert_one(
        "INSERT INTO app_user (email, first_name, last_name, entity_id) "
        "VALUES (%s, %s, %s, %s) RETURNING id",
        ("morgan.lee@acmecorp.com", "Morgan", "Lee", acme_id),
    )

    ml_id = insert_one(
        "INSERT INTO master_license (master_license_ref, entity_id, label, program, sponsor) "
        "VALUES (%s, %s, %s, %s, %s) RETURNING id",
        ("ML-DEMOACME", acme_id, "Acme Corp Master", "STD", "STANDARD"),
    )

    start_date = TODAY - timedelta(days=180)
    expiry_date = TODAY + timedelta(days=47)  # "urgent but not expired" — per plan
    lic_id = insert_one(
        "INSERT INTO license (license_ref, master_license_id, status, start_date, expiry_date) "
        "VALUES (%s, %s, %s, %s, %s) RETURNING id",
        ("L-DEMOACME", ml_id, "active", start_date, expiry_date),
    )

    ml_product_id = conn.execute("SELECT id FROM product WHERE product_code = 'ML'").fetchone()[0]
    sl_product_id = conn.execute("SELECT id FROM product WHERE product_code = 'SL'").fetchone()[0]

    matlab_lp_id = insert_one(
        "INSERT INTO license_product (master_license_id, license_id, product_id, seat_count, business_offering_id) "
        "VALUES (%s, %s, %s, %s, %s) RETURNING id",
        (ml_id, lic_id, ml_product_id, 10, 4000 + ml_product_id),
    )
    simulink_lp_id = insert_one(
        "INSERT INTO license_product (master_license_id, license_id, product_id, seat_count, business_offering_id) "
        "VALUES (%s, %s, %s, %s, %s) RETURNING id",
        (ml_id, lic_id, sl_product_id, 5, 4000 + sl_product_id),
    )

    granted_at = TODAY - timedelta(days=200)
    matlab_ent_id = insert_one(
        "INSERT INTO entitlement (license_id, master_license_id, license_product_id, product_id, "
        "entitlement_type, activation_type, status, granted_at) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
        (lic_id, ml_id, matlab_lp_id, ml_product_id, "license", "designated_computer", "active", granted_at),
    )
    simulink_ent_id = insert_one(
        "INSERT INTO entitlement (license_id, master_license_id, license_product_id, product_id, "
        "entitlement_type, activation_type, status, granted_at) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
        (lic_id, ml_id, simulink_lp_id, sl_product_id, "license", "standalone_named_user", "active", granted_at),
    )

    conn.execute(
        "INSERT INTO policy (entitlement_id, policy_name, quantity, max_activations, "
        "activation_ttl_days, allow_offline, reactivation_limit) VALUES (%s, %s, %s, %s, %s, %s, %s)",
        (matlab_ent_id, "Designated Computer", 10, 10, 90, False, 1),
    )
    conn.execute(
        "INSERT INTO policy (entitlement_id, policy_name, quantity, max_activations, "
        "activation_ttl_days, allow_offline, reactivation_limit) VALUES (%s, %s, %s, %s, %s, %s, %s)",
        (simulink_ent_id, "Named User", 5, 1, 30, False, 0),  # TTL 30d — the Story-2 stale-seat signal
    )

    conn.execute(
        "INSERT INTO entitlement_person (entitlement_id, user_id, role, added_date, status) "
        "VALUES (%s, %s, %s, %s, %s)",
        (simulink_ent_id, jane_id, "user", TODAY - timedelta(days=150), "active"),
    )

    last_heartbeat = datetime(TODAY.year, TODAY.month, TODAY.day) - timedelta(days=94)
    conn.execute(
        "INSERT INTO activation (entitlement_id, user_id, machine_id, machine_name, os, "
        "activation_date, last_heartbeat, status) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
        # status 'active' (still holding the slot) but a long-stale heartbeat — the
        # realistic Story-2 setup: revoke flips it active -> inactive, freeing the slot.
        (simulink_ent_id, jane_id, "MAC-OLD-7291", "Janes-MacBook-Pro", "macOS 15",
         (last_heartbeat - timedelta(days=45)).date(), last_heartbeat, "active"),
    )

    # Fill license_end_user to 10/10 on MATLAB's seat_count (all 10 seat-holders; admin excluded).
    for uid in user_ids:
        conn.execute(
            "INSERT INTO license_end_user (license_id, user_id, added_date, status) "
            "VALUES (%s, %s, %s, %s)",
            (lic_id, uid, TODAY - timedelta(days=170), "active"),
        )

    conn.execute(
        "INSERT INTO master_license_admin (master_license_id, user_id, renewal_notifications, added_date) "
        "VALUES (%s, %s, %s, %s)",
        (ml_id, admin_id, True, TODAY - timedelta(days=180)),
    )

    print("plant-demo:")
    print(f"  entity Acme Corp             id={acme_id}")
    print(f"  master_license ML-DEMOACME   id={ml_id}")
    print(f"  license L-DEMOACME           id={lic_id}  expiry={expiry_date} (+47d)")
    print(f"  license_product MATLAB       id={matlab_lp_id}  seats=10 (10/10 filled)")
    print(f"  license_product Simulink     id={simulink_lp_id}  seats=5")
    print(f"  entitlement MATLAB           id={matlab_ent_id}")
    print(f"  entitlement Simulink         id={simulink_ent_id}  policy TTL=30d (named-user)")
    print(f"  user jane.doe@acmecorp.com   id={jane_id}  -> Simulink, stale activation MAC-OLD-7291 (94d)")
    print(f"  admin morgan.lee@acmecorp.com id={admin_id}")


def fix_sequences(conn):
    """Explicit-id COPY leaves identity sequences at 1 → bump each past max(id)."""
    tables = ["product", "entity", "app_user", "master_license", "license", "license_product",
              "entitlement", "policy", "entitlement_person", "activation",
              "license_end_user", "master_license_admin"]
    for t in tables:
        conn.execute(
            f"SELECT setval(pg_get_serial_sequence('{t}','id'), "
            f"COALESCE((SELECT max(id) FROM {t}), 1), true)")


def verify(conn):
    print("\n── verify ──")
    tables = ["product", "product_suite_component", "entity", "app_user", "master_license",
              "license", "license_product", "entitlement", "policy", "entitlement_person",
              "activation", "license_end_user", "master_license_admin"]
    total = 0
    for t in tables:
        n = conn.execute(f"SELECT count(*) FROM {t}").fetchone()[0]
        total += n
        print(f"  {t:24} {n:>12,}")
    print(f"  {'TOTAL':24} {total:>12,}")
    # FK integrity spot checks (should all be 0)
    checks = {
        "entitlement→license": "SELECT count(*) FROM entitlement e LEFT JOIN license l ON e.license_id=l.id WHERE l.id IS NULL",
        "activation→entitlement": "SELECT count(*) FROM activation a LEFT JOIN entitlement e ON a.entitlement_id=e.id WHERE e.id IS NULL",
        "activation→user": "SELECT count(*) FROM activation a LEFT JOIN app_user u ON a.user_id=u.id WHERE u.id IS NULL",
        "policy 1:1 orphans": "SELECT count(*) FROM entitlement e LEFT JOIN policy p ON p.entitlement_id=e.id WHERE p.id IS NULL",
    }
    print("  FK integrity (expect 0):")
    for name, q in checks.items():
        print(f"    {name:26} {conn.execute(q).fetchone()[0]}")
    # a couple of realism signals
    stale = conn.execute(
        "SELECT count(*) FROM activation WHERE now() - last_heartbeat > interval '60 days'").fetchone()[0]
    unalloc = conn.execute("SELECT count(*) FROM license_product WHERE license_id IS NULL").fetchone()[0]
    print(f"  stale activations (>60d): {stale:,}")
    print(f"  unallocated products:     {unalloc:,}")


if __name__ == "__main__":
    sys.exit(main())
